server:
  port: 8888

user:
  out: helloworld

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /test
    disable-swagger-default-url: on
  packages-to-scan: com.hnu.testProject

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
